services:
  mysql:
    image: mysql:8.0
    container_name: tfg_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda_online
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: php:8.2-apache
    container_name: tfg_web
    ports:
      - "8081:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data: